config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'restaurants#index'

  resources :restaurants do 
    resources :reviews
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews
	validates :name, presence: true, format: {with: /\A[A-Z]/, message: 'has to start with a capital letter'}
	validates :cuisine, presence: true, length: {minimum: 3}

	def average_rating
		reviews.none? ? "N/A" : reviews.inject(0) {|acc, rev| acc + rev.rating} / reviews.count.to_f
	end


end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	before_action :authenticate_user!, except: [:index]

	def index
		@restaurants = Restaurant.all
		@review = Review.new
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		Restaurant.create(restaurant_params)
		redirect_to '/restaurants'
	end

	def edit
		@restaurant = Restaurant.find params[:id]
	end

	def update
		@restaurant = Restaurant.find params[:id]
		@restaurant.update restaurant_params
		redirect_to '/restaurants'
	end

	def destroy
		@restaurant = Restaurant.find params[:id]
		@restaurant.destroy
		flash[:notice] = "Successfully deleted #{@restaurant.name}"
		redirect_to '/restaurants'
	end

	private

	def restaurant_params
		params.require(:restaurant).permit(:name, :cuisine)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def new
		@restaurant = Restaurant.find params[:restaurant_id]
		@review = Review.new
	end

	def create
		@restaurant = Restaurant.find params[:restaurant_id]
		@review = @restaurant.reviews.create review_params
		flash[:notice] = "Review created"
		redirect_to '/restaurants' unless request.xhr?
	end

	private

	def review_params
		params.require(:review).permit(:thoughts, :rating)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper


	def star_rating(number)
		return 'N/A' unless number.is_a? Numeric
		round = number.round
		return ("★" * round) + ("☆" * (5 - round))
	end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myyelp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  <%= link_to('Edit User Details', edit_user_registration_path) %>
<% else %>
  <%= link_to('Login', new_user_session_path)  %>  
  <%= link_to('Sign up', new_user_registration_path)  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>


<%= f.label :cuisine %>
<%= f.text_field :cuisine %>

<%= f.submit %>

<%end%>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <ul>
  <% @restaurants.each do |restaurant| %>
    <li class='restaurant'><%= restaurant.name %> (<%= restaurant.cuisine %>) <br>
      Average rating: 

      <span class='average_rating'>
        <%= star_rating(restaurant.average_rating) %>
      </span>  <br>
      <% if user_signed_in?%>
	      <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant.id) %>  <br>
	      <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant.id), method: :delete, 'data-confirm' => 'Are sure you want to delete this?' %>  <br>
	      <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant.id) %>  <br>
      <% end %>
      <ul class='reviews'>
        <% restaurant.reviews.each do |review| %>
          <li><%= review.thoughts %> (<%= star_rating review.rating %>)</li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
	      <%= form_for [restaurant, @review] do |f| %>
	        <%= f.label :thoughts %>
	        <%= f.text_area :thoughts %>

	        <%= f.label :rating %>
	        <%= f.select :rating, 1..5 %>

	        <%= f.submit %>
	      <% end %>
	     <% end %>
    </li>
  <% end %>
  </ul>
<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<%= link_to 'Create restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
	
	<%= f.label :thoughts %>
	<%= f.text_area :thoughts %>

	<%= f.label :rating %>
	<%= f.select :rating, 1..5 %>

	<%= f.submit %>

<% end %>